name: Build RPM

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - release/*

jobs:
  build-rpm:
    runs-on: ubuntu-latest

    container:
      image: goreleaser/nfpm
      options: --entrypoint ""

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build RPM package
        run: nfpm package --config nfpm.yaml --packager rpm

      - name: Detect rpm filename
        id: detect
        run: echo "RPM_FILE=$(ls *.rpm)" >> $GITHUB_ENV

      - name: Upload RPM artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.RPM_FILE }}
          path: ${{ env.RPM_FILE }}
          retention-days: 7
